extends SceneTree

const Appearance = preload("res://scripts/data/hero_appearance_definition.gd")
const HeroCompositor = preload("res://scripts/visual/hero_compositor.gd")

func _init() -> void:
	var appearance: Resource = Appearance.new()
	appearance.set("eyes_style", "friendly")
	appearance.set("iris_style", "ring")
	appearance.set("pupil_style", "round")
	appearance.set("brows_style", "soft")
	appearance.set("mouth_style", "smile")
	appearance.set("expressions_enabled", true)
	appearance.set("idle_expression", "heroic")
	appearance.set("move_expression", "focused")
	appearance.set("attack_expression", "angry")
	appearance.set("cast_expression", "mystic")
	appearance.set("hit_expression", "hurt")
	appearance.set("ko_expression", "ko")
	appearance.set("portrait_expression", "cheerful")
	appearance.set("portrait_direction", "front")
	assert(String(appearance.call("expression_for_state", "attack")) == "angry")
	assert(String(appearance.call("expression_part_override", "eyes", "angry")) == "angry")
	assert(String(appearance.call("expression_part_override", "iris", "ko")) == "none")
	for state: String in HeroCompositor.STATES:
		var frame: Image = HeroCompositor.compose_frame(appearance, "front", state)
		assert(frame != null)
		assert(frame.get_size() == HeroCompositor.FRAME_SIZE)
	var atlas: Image = HeroCompositor.compose_atlas(appearance)
	assert(atlas.get_size() == Vector2i(HeroCompositor.FRAME_SIZE.x * 6, HeroCompositor.FRAME_SIZE.y * 4))
	appearance.set("expressions_enabled", false)
	assert(String(appearance.call("expression_for_state", "attack")) == "base")
	print("[V1.26] Hero Creator Expressions & Profiles smoke test OK")
	quit()
