class_name SporeUnitData
extends RefCounted

## Transitional V1.0 unit model.
## The battle controller still consumes Dictionaries, but all mandatory fields are created here.
## This gives one schema boundary now and allows a later migration to typed Resources without changing catalogs.


static func create(
	id: String,
	unit_name: String,
	role: String,
	team: String,
	position: Vector2i,
	hp: int,
	attack: int,
	move_range: int,
	attack_range: int,
	color: Color,
	special: String,
	initiative: int,
	secondary: String
) -> Dictionary:
	return {
		"id": id,
		"name": unit_name,
		"role": role,
		"team": team,
		"pos": position,
		"hp": hp,
		"max_hp": hp,
		"attack": attack,
		"physical_power": attack,
		"magic_power": maxi(1, int(round(float(attack) * 0.75))),
		"physical_defense": 0,
		"magic_defense": 0,
		"move": move_range,
		"range": attack_range,
		"attack_min_range": 1,
		"attack_max_range": attack_range,
		"threat_min_range": 1,
		"threat_max_range": 1,
		"weapon_family": "unarmed",
		"can_opportunity_attack": true,
		"basic_attack_damage_type": "physical",
		"shield_block_chance": 0,
		"shield_block_reduction": 0,
		"color": color,
		"visual_id": id,
		"special": special,
		"initiative": initiative,
		"accuracy": 0,
		"evasion": 0,
		"ct": 0,
		"casting": {},
		"downed": false,
		"downed_countdown": 0,
		"removed_from_battle": false,
		"end_ct_bonus": 0,
		"basic_attack_damage_bonus": 0,
		"basic_attack_accuracy_bonus": 0,
		"flat_damage_reduction": 0,
		"focus_regen_bonus": 0,
		"revive_hp_bonus": 0,
		"jump_up_bonus": 0,
		"jump_down_bonus": 0,
		"ignore_opportunity": false,
		"facing": Vector2i(0, -1) if team == "player" else Vector2i(0, 1),
		"statuses": {},
		"has_moved": false,
		"has_acted": false,
		"reaction_used": false,
		"max_focus": 2,
		"focus": 2,
		"cooldowns": {},
		"secondary": secondary,
		"boss_phase": 1,
	}
